Claims/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
  put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
 end
  resources :users
  resources :claims

  get '/claims/:id/attachments' => 'claims#attachments'
  
	
 post '/claim/pay' => 'claims#pay', as: :pay_claim
  get '/user/:id/admin' => 'users#admin', as: :make_admin
  

  root 'users#show'
  
	

end

Claims/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable, :recoverable, :registerable, :encryptable
  has_many :claims

  validates :email, email_format: { message: "doesn't look like an email address" }
  validates :email, presence: true
  validates :email, uniqueness: true
  
  #validates :password, :presence => true, :confirmation => true, :length => {:within => 6..40}

 def after_password_reset
  # self.update_attribute(:invite_code, nil)
 end

def self.options_for_select
  order('LOWER(email)').map { |e| [e.email, e.id] }
end

 attr_accessor :login
 

 def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions.to_hash).first
      end
    end 


def active_for_authentication?
  super && self.active? 
end

def inactive_message
  "Sorry, this account has been deactivated."
end


end

Claims/app/controllers/users_controller.rb
class UsersController < ApplicationController

before_filter :check_admin?, :only => [:index]
def show
    store_location
   #if params[:filterrific].nil?
   #     params[:filterrific]={"with_user_id" => current_user.id}
   #else
   #    params[:filterrific]["with_user_id"]=current_user.id
   #end   
  # @claims=current_user.claims
	@filterrific = initialize_filterrific(
		    Claim,
		    params[:filterrific],
                    select_options: {
		    sorted_by: Claim.options_for_sorted_by,
                   				
			},
                  
                   :persistence_id => false,
 
		  ) or return
		  @claims = @filterrific.find
                  @claims = @claims.where("user_id = ?", current_user.id)
		  @claims = @claims.paginate(:page => params[:page], :per_page => 10)
		  respond_to do |format|
		    format.html
		    format.js
		  end
	    rescue ActiveRecord::RecordNotFound => e
	    # There is an issue with the persisted param_set. Reset it.
	    puts "Had to reset filterrific params: #{ e.message }"
	    redirect_to(reset_filterrific_url(format: :html)) and return

	#current_user.update_attribute :admin, true
end


def index
 @users=User.all
end


def destroy
                #Claim.find_by_user_id(params[:id]).destroy
		if User.find(params[:id]).update_attribute(:active, false)
    			flash[:notice] = "User account deactivated"
		        redirect_to '/users'
	                
		else
			flash[:notice] = "Unable to deactivate User"
		end
end

def admin
              @user = User.find(params[:id])
         
              if @user.update_attribute(:admin, true)

                 redirect_to '/users'
              else
                 flash[:notice] = "Unable to make admin"
              end  
end

def check_admin?
		if current_user && !current_user.admin?
			flash[:notice] = "You do not have permission to perform this action."
			redirect_to root_url
			return; 
		end
	end

		
	
end

Claims/app/helpers/users_helper.rb
module UsersHelper
end

Claims/app/views/users/_list.html.erb
<style type="text/css">

.item{
    background: #333;    
    text-align: center;
    height: 300px !important;
}
.carousel{
    margin-top: 20px;
}
.bs-example{
	margin: 20px;
}
</style>


<div id="filterrific_results">


   <div>
    <%= page_entries_info claims %>
  </div>
  <table class="table table-striped">
    <tr>
      <th>Title</th>
      <th>Created At</th>
      <th>Amount</th>
      <th>Status</th>
      
      <th>View Claim</th> 
      <th></th>
      <th></th>
      <th></th>   	
   </tr>
    <% total=0 %>
    <% claims.each do |c| %>
      <tr>
       
        <td><%= c.title %></td>
         <td><%= c.created_at.strftime("%d/%m/%Y") %></td>
         <td><%= c.amount %></td>
        <td><%= c.status %></td>

 <td> <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#claim-<%= c.id %>"> View Claim </button>	
	
	<div class="modal fade" id="claim-<%= c.id %>" tabindex="-1" role="dialog" aria-labelledby="claim-<%= c.id %>-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title" id="claim-<%= c.id %>-label"> <%= c.title %></h1>
        </div>
        <div class="modal-body">
		<dl class="dl-horizontal">		
		<dt>Date of Expenditure: </dt> 	<dd><%= c.exp_date %> </dd>          
		<dt> Created At:  </dt>		<dd><%= c.created_at %>	      </dd>
		<dt> Summary:  </dt>		<dd><%= c.summary %>	      </dd>
	  	<dt> Amount: </dt> 		<dd>Rs. <%= c.amount %>	      </dd>
	  	<dt> Status: </dt>		<dd><%= c.status %>	      </dd>
		</br> <dd> <% c.bills.all.each do |p| %>
      

     <% if p.content_type == "application/pdf" %>  
      <%= link_to image_tag("pdf.jpg") , "/claims/#{c.id}/attachments", :remote => true %>
      <% else %>
      <%= link_to image_tag(p.file_url(:thumb)) , "/claims/#{c.id}/attachments", :remote => true %>
      <% end %>


       
          
                               <% end %>
		 </dd>
                </dl>
	</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

	</td>



        <% if c.status=="Unpaid" %>
       <td> <%= button_to 'Update Claim', edit_claim_path(c.id), {class: "btn btn-primary btn-sm",method: :get} %></td>
     <td><%= button_to 'Delete', c,{class: "btn btn-primary btn-sm",method: :delete, data: { confirm: "Are you sure?" } }  %></td>
       <% else %> <td colspan= 2></td>
       <% end %>


<% unless c.bills.empty? %>

<td>


  
   <%= link_to "Attachments", "/claims/#{c.id}/attachments", :remote => true, :class => 'btn btn-primary' %>

   
	</td>


<% else %>
<td></td>
<% end %>




       </tr>
       <% total=total+c.amount %> 
    <% end %>
  <tr> <td></td> <td></td> <td>  <h4> Total: <%= total.round(2) %> </h4></td> <td></td> <td></td> <td></td> <td></td> <td></td></tr>
  </table>
  
</div>
<div style="font-size: 20px">
<%= will_paginate claims %></div>
</br></br></br></br></br>



  <div class="modal fade" id="claim-attachments" tabindex="-1" role="dialog" aria-labelledby="claim-label" aria-hidden="true">
   
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1>BILLS</h1>
        </div>
        <div class="modal-body">
    
<div class="bs-example" id="bills">
    
</div>





  </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

Claims/app/views/users/index.html.erb
<%= yield %>
<div class="page-header">
    <h1>Manage Users: <small>A list of all users</small></h1>
</div>
<div class="container">

<table class="table">

<tr class="success">

<th> Email Id </th>
<th> Delete </th>
<th> Admin</th>
</tr>

<% @users.each do |u| %>


<% if !u.admin? && u.active? %> 
<tr class="info">
<td> <%= u.email %> </td>
<td><%= button_to 'Deactivate Account', u,{method: :delete, class: "btn btn-primary btn-sm", data: { confirm: "Are you sure?" }}  %></td>
<td><%= button_to 'Make Admin ',make_admin_path(u.id),{ method: :get, class: "btn btn-primary btn-sm", data: { confirm: "Are you sure?" }}  %></td>
</tr>
<% elsif u.admin? %>
<tr class="info">
<td> <%= u.email %> </td>
<td> Cannot Delete </td>
<td> Already Admin</td>
</tr>
<% else %>
<tr class="info">
<td> <%= u.email %> </td>
<td colspan="2"> Account Deactivated </td>
</tr>
<% end %> 

	
<% end %>


</table>
</div>

<br/><br/>

Claims/app/views/users/show.html.erb
<style>
.link {color: white;
       text-decoration:none
       
       }
.link:hover {color: white;
              text-decoration:none}
</style>


<%= yield %>


<h1>Your Claims</h1></br>
<div class="well">

<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
  <div class="row">
  <div class="col-md-2">
    Title<br/>
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query, class: 'form-control'
      ) %>
  </div>
  
 <div class="col-md-2">
    Registered after
    <%= f.text_field(:with_created_at_gte,{ class: 'js-datepicker form-control'}) %>
  </div>
 
 <div class="col-md-2">
    Amount Greater than
    <%= f.number_field(:with_amount_gte, class: 'form-control') %>
 </div>

  <div class="col-md-2">
    Status<br/>
   Paid <%= f.radio_button :with_status, "Paid", class: 'radio-inline'  %>
   Unpaid <%= f.radio_button :with_status, "Unpaid" , class: 'radio-inline' %>
 </div>


 <div class="col-md-2">
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by],{ include_blank: '- Any -' },{class: 'form-control'} ) %>
 </div>
</div><br/>


<div class="row">
<div class="col-md-1">  
<%= f.submit 'Filter' , class: "btn btn-primary" %>
</div>

 <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
 
 <div class="col-md-1">
	<span class="btn btn-primary">
    <%= link_to('Reset filters',
      reset_filterrific_url, class: "link"
    ) %>
	</span>

 </div>
 
</div>
</div>

<% end %>
</div>
<%= render(
  partial: 'users/list',
  locals: { claims: @claims }
) %>

<script type="text/javascript">
  $('.js-datepicker').datepicker();	
  </script>